### ISSUE TITLE
記事のリンクが長すぎるとはみでる

### ISSUE THREAD

**Issue by ittokunvim** [ittoku-ky73/ittoku-tech#78]
**取り組むイシューの内容**

記事のリンクの文字列が長すぎると枠からはみ出るので、それを修正します。

**実装手順**

- [x] `src/app/articles/[slug]/page.module.css`を修正

**Comment by ittokunvim** [comment]
リンクに以下のスタイルを適用することによって修正が可能。

```css
a {
  overflow-wrap: break-word;
}
```
